### PR TITLE
add arm64 arch

### PR DESCRIPTION
**Pull request by ray-harris**
Signed-off-by: Ray Harris <raharris@redhat.com>

https://github.com/stolostron/backlog/issues/19870

### CODE REVIEW

**Review by zkayyali812 — APPROVED** [review]

**Comment by elgnay** [comment]
@ray-harris This chart is moving from MCH to MCE, is this update still necessary?

**Comment by ray-harris** [comment]
@zkayyali812 Can you speak to @elgnay 's question?

**Comment by ray-harris** [comment]
Closing as this chart is being moved to MCE.

**Comment by ray-harris** [comment]
Reopening as the klusterlet addon deployment part of CLC is not moving to MCE.

**Pull request merged**
